### ISSUE TITLE
Group listing | Fix mobile responsiveness

### ISSUE THREAD

**Issue by bidyut-majumdar** [Bitovn-Micro-Services/groups-issues#236]

**Comment by Anupriyabanger** [comment]
Not able to check, as not able to open Groups on Mobile

https://github.com/Bitovn-Micro-Services/groups-issues/assets/109590553/833d6e77-05f3-42a6-9e68-f06e2e95fcd8

**Comment by bidyut-majumdar** [comment]
@Anupriyabanger thats header redirection issue. please ask @manojnegi07 if you're facing issue on this. Since listing responsiveness issue was already corrected putting review required again .

**Comment by Anupriyabanger** [comment]
Still facing same issue

https://github.com/Bitovn-Micro-Services/groups-issues/assets/109590553/da0d06d0-eb66-45da-9326-4e9e420431f3
